version: "3.8"
services:
  nginx-proxy-manager:
    hostname: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' 
      - '443:443' 
      - '81:81' 
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
 
  frontend:
    hostname: frontend
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    env_file:
      - frontend/.env
    ports:
      - "5173:5173"
 
  backend:
    hostname: backend
    image: backend-latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      /bin/bash -c "poetry run bash prestart.sh && poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
 
  adminer:
    hostname: adminer
    image: adminer
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
 
volumes: 
  data:
  letsencrypt:
